import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Global Data",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script
          type="module"
          src="https://unpkg.com/@google/model-viewer/dist/model-viewer.min.js"
        ></script>
      </head>
      <body className={`${inter.className}`}>
        <header>
          <div className="headerLogo">
            <h2>Global Data | WDI</h2>
          </div>
          
          <nav className="headerNav">
            <Link href="">Home</Link>
            <Link href="">How does it work?</Link>
            <Link href="" className="wdiHeader">World Development Indicators</Link>
          </nav>
        </header>
        {children}
        <footer>
          Developed and Designed by Sergio García López |
          <span>
            <Link href="https://github.com/sergiosoftdev2" target="blank"><img src="https://img.icons8.com/ios11/512/FFFFFF/github.png"/></Link>
            <Link href="https://www.linkedin.com/in/sergiosoftdev/" target="blank"><img src="https://e7.pngegg.com/pngimages/753/965/png-clipart-linkedin-linkedin.png"/></Link>
          </span>
        </footer>
      </body>
    </html>
  );
}
